### PR TITLE
Add support for the current version of the Play Store

### LINKED ISSUE #12: Crash
Causes a crash when installing/updating apps. Play store version 5.10.30 on Android 4.4.4 on a Nexus 5.

Relevant logs:

```
11-04 06:44:43.976 E/AndroidRuntime(32316): FATAL EXCEPTION: main
11-04 06:44:43.976 E/AndroidRuntime(32316): Process: com.android.vending, PID: 32316
11-04 06:44:43.976 E/AndroidRuntime(32316): java.lang.NoSuchFieldError: com.google.android.finsky.layout.AppPermissionAdapter#mData
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:80)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:611)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.germainz.playpermissionsexposed.XposedMod$2.replaceHookedMethod(XposedMod.java:199)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:15)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.layout.AppPermissionAdapter.getCount(Native Method)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.layout.AppSecurityPermissions.showPermissions(AppSecurityPermissions.java:81)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.layout.AppSecurityPermissions.bindInfo(AppSecurityPermissions.java:70)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.activities.AppsPermissionsActivity.onDataChanged(AppsPermissionsActivity.java:7342)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.api.model.DfeModel.notifyDataSetChanged(DfeModel.java:104)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.api.model.DfeDetails.onResponse(DfeDetails.java:1091)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.api.DfeRequest.deliverResponse(DfeRequest.java:20726)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at android.os.Handler.handleCallback(Handler.java:733)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at android.os.Looper.loop(Looper.java:136)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at java.lang.reflect.Method.invoke(Method.java:515)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at dalvik.system.NativeStart.main(Native Method)
```

### PR DESCRIPTION
**Pull request by pR0Ps**
Testing and working on Android 4.4.4, Play Store v6.0.5 (current).

From looking at the decompiled code of different Play Store versions it should support all the way back to v5.4.x.

I also converted it to an Android Studio project to make it easier to build.

This fixes #12

### CODE REVIEW

**Comment by pR0Ps** [comment]
I'll rebase this

**Comment by pR0Ps** [comment]
Rebased on top of the current master.

**Comment by GermainZ** [comment]
I already have locally, no need. Can't push right now though.

On Sun, Jan 17, 2016 at 6:06 PM, Carey Metcalfe < notifications@github.com [notifications@github.com] > wrote:
I'll rebase this

—
Reply to this email directly or view it on GitHub
[https://github.com/GermainZ/PlayPermissionsExposed/pull/13#issuecomment-172345003] .[https://github.com/notifications/beacon/ACxRlbjEbyt0_Q_qCTJulUCpAbu7DhHEks5pa7OWgaJpZM4HGXdn.gif]

**Comment by GermainZ** [comment]
All merged and pushed, thanks a lot for the PR and apologies for the delay! :+1:

4b7dd66e6728a616aadb71ea21a4ac3825074625
320eb635b0748f4264a3e622eb9c140fcdd915dc
c2a375ba90060dae2f5ead191c8ae99c0c660d06
6e84ae76637f2ac3cf19500ff93f4fdcbcc32762

**Pull request closed without merging**
